version: '3.9'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: postgres:latest
    container_name: postgres-container
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: mydb
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'prisma']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
